import { Raleway, Roboto, Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const geistSans = Raleway({
});

const openSans = Roboto({
});

const JosefinSans = Josefin_Sans({
});

export const metadata = {
  title: "Viraj",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  }
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}</body>
    </html>
  );
}
